repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false

      - id: vulture
        name: vulture
        entry: vulture  app.py ingest.py rag_chat.py query_cli.py
        language: system
        pass_filenames: false

      - id: bandit
        name: bandit
        entry: bandit app.py ingest.py rag_chat.py query_cli.py
        language: system
        pass_filenames: false
